set_property PACKAGE_PIN V8 [get_ports FCLK_CLK0]
set_property IOSTANDARD LVCMOS33 [get_ports FCLK_CLK0]

set_property PACKAGE_PIN Y9 [get_ports MCLK]
set_property PACKAGE_PIN P16 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property PACKAGE_PIN W12 [get_ports SCL_1]
set_property PACKAGE_PIN W11 [get_ports SCL_2]
set_property PACKAGE_PIN V10 [get_ports SDA_1]
set_property PACKAGE_PIN W8 [get_ports SDA_2]
set_property IOSTANDARD LVCMOS33 [get_ports SDA_2]
set_property IOSTANDARD LVCMOS33 [get_ports SCL_1]
set_property IOSTANDARD LVCMOS33 [get_ports SCL_2]
set_property IOSTANDARD LVCMOS33 [get_ports SDA_1]

set_property PACKAGE_PIN F22 [get_ports FILTER_ON]
set_property PACKAGE_PIN T22 [get_ports RUNNING]
set_property IOSTANDARD LVCMOS33 [get_ports RUNNING]
set_property IOSTANDARD LVCMOS18 [get_ports FILTER_ON]
