set_property PACKAGE_PIN U14 [get_ports FCLK_CLK0]
set_property IOSTANDARD LVCMOS33 [get_ports FCLK_CLK0]

set_property PACKAGE_PIN F22 [get_ports {SW_Inputs[0]}]
set_property PACKAGE_PIN G22 [get_ports {SW_Inputs[1]}]
set_property PACKAGE_PIN H22 [get_ports {SW_Inputs[2]}]
set_property PACKAGE_PIN F21 [get_ports {SW_Inputs[3]}]
set_property PACKAGE_PIN H19 [get_ports {SW_Inputs[4]}]
set_property PACKAGE_PIN H18 [get_ports {SW_Inputs[5]}]
set_property PACKAGE_PIN H17 [get_ports {SW_Inputs[6]}]
set_property PACKAGE_PIN M15 [get_ports {SW_Inputs[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_Inputs[0]}]

set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W12 [get_ports scl]
set_property PACKAGE_PIN W11 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property IOSTANDARD LVCMOS33 [get_ports scl]

set_property PACKAGE_PIN T22 [get_ports {status[3]}]
set_property PACKAGE_PIN T21 [get_ports {status[2]}]
set_property PACKAGE_PIN U22 [get_ports {status[1]}]
set_property PACKAGE_PIN U21 [get_ports {status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status[0]}]
