webtalk_init -webtalk_dir D:\\UTFPR\\TCC\\pothole_detector\\PS_PL_COM\\PS_PL_COM.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-07 17:00:19" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1o2urqvbkv8l0mllv4mm6qeb59" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2295 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.517 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1575744557153" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key hwid -value "1566588623266" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key bspid -value "1568468723148" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key projSize -value "184.97265625" -context "sdk\\\\application/1575744557153"
webtalk_add_data -client sdk -key uid -value "1575745005436" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key hwid -value "1566588623266" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key bspid -value "1568468723148" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key projSize -value "594.30859375" -context "sdk\\\\application/1575745005436"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1575745218891"
webtalk_transmit -clientid 3138431339 -regid "" -xml D:\\UTFPR\\TCC\\pothole_detector\\PS_PL_COM\\PS_PL_COM.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\UTFPR\\TCC\\pothole_detector\\PS_PL_COM\\PS_PL_COM.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\UTFPR\\TCC\\pothole_detector\\PS_PL_COM\\PS_PL_COM.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
