function filter_generatehdl(filtobj)
%  FILTER_GENERATEHDL   Function to generate HDL for filter object.
%  Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
%  Generated on: 2019-07-27 23:38:40
%  -------------------------------------------------------------
%  HDL Code Generation Options:
%  TargetLanguage: VHDL
%  UseRisingEdge: on
%  TestBenchStimulus: step ramp chirp 
%  GenerateHDLTestbench: on
% 
%  Filter Settings:
%  Discrete-Time IIR Filter (real)
%  -------------------------------
%  Filter Structure    : Direct-Form II, Second-Order Sections
%  Number of Sections  : 1
%  Stable              : Yes
%  Linear Phase        : No
%  Arithmetic          : fixed
%  Numerator           : s16,13 -> [-4 4)
%  Denominator         : s16,14 -> [-2 2)
%  Scale Values        : s16,24 -> [-1.953125e-03 1.953125e-03)
%  Input               : s16,15 -> [-1 1)
%  Section Input       : s16,18 -> [-1.250000e-01 1.250000e-01)
%  Section Output      : s16,10 -> [-32 32)
%  Output              : s16,10 -> [-32 32)
%  State               : s16,15 -> [-1 1)
%  Numerator Prod      : s32,28 -> [-8 8)
%  Denominator Prod    : s32,29 -> [-4 4)
%  Numerator Accum     : s40,28 -> [-2048 2048)
%  Denominator Accum   : s40,29 -> [-1024 1024)
%  Round Mode          : convergent
%  Overflow Mode       : wrap
%  Cast Before Sum     : true

%  -------------------------------------------------------------

% Generating HDL code
generatehdl(filtobj, 'TargetLanguage', 'VHDL',... 
               'UseRisingEdge', 'on',... 
               'TestBenchStimulus',  {'step', 'ramp', 'chirp'},... 
               'GenerateHDLTestbench', 'on');

% [EOF]
