-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.4 and Filter Design HDL Coder 3.1.3.
-- Generated on: 2019-08-15 19:12:35
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- UseRisingEdge: on
-- TestBenchStimulus: step ramp chirp 

-- Filter Specifications:
--
-- Sample Rate   : N/A (normalized frequency)
-- Response      : Lowpass
-- Specification : N,F3dB
-- Filter Order  : 2
-- 3-dB Point    : 0.25
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 1
-- Stable              : Yes
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s32,29 -> [-4 4)
-- Denominator         : s32,30 -> [-2 2)
-- Scale Values        : s32,34 -> [-1.250000e-01 1.250000e-01)
-- Input               : s16,0 -> [-32768 32768)
-- Section Input       : s16,12 -> [-8 8)
-- Section Output      : s16,10 -> [-32 32)
-- Output              : s16,0 -> [-32768 32768)
-- State               : s16,15 -> [-1 1)
-- Numerator Prod      : s48,44 -> [-8 8)
-- Denominator Prod    : s48,45 -> [-4 4)
-- Numerator Accum     : s50,44 -> [-32 32)
-- Denominator Accum   : s50,45 -> [-16 16)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT scaleconst1                    : signed(31 DOWNTO 0) := to_signed(1677289061, 32); -- sfix32_En34
  CONSTANT coeff_b1_section1              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_b2_section1              : signed(31 DOWNTO 0) := to_signed(1073741824, 32); -- sfix32_En29
  CONSTANT coeff_b3_section1              : signed(31 DOWNTO 0) := to_signed(536870912, 32); -- sfix32_En29
  CONSTANT coeff_a2_section1              : signed(31 DOWNTO 0) := to_signed(-1012333500, 32); -- sfix32_En30
  CONSTANT coeff_a3_section1              : signed(31 DOWNTO 0) := to_signed(357913941, 32); -- sfix32_En30
  -- Signals
  SIGNAL input_register                   : signed(15 DOWNTO 0); -- sfix16
  SIGNAL scale1                           : signed(57 DOWNTO 0); -- sfix58_En44
  SIGNAL mul_temp                         : signed(47 DOWNTO 0); -- sfix48_En34
  SIGNAL scaletypeconvert1                : signed(15 DOWNTO 0); -- sfix16_En12
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL a2sum1                           : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL b1sum1                           : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL b2sum1                           : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL typeconvert1                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv1                       : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL a2mul1                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL a3mul1                           : signed(47 DOWNTO 0); -- sfix48_En45
  SIGNAL b1mul1                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b2mul1                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL b3mul1                           : signed(47 DOWNTO 0); -- sfix48_En44
  SIGNAL sub_cast                         : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL sub_cast_1                       : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL sub_temp                         : signed(50 DOWNTO 0); -- sfix51_En45
  SIGNAL sub_cast_2                       : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL sub_cast_3                       : signed(49 DOWNTO 0); -- sfix50_En45
  SIGNAL sub_temp_1                       : signed(50 DOWNTO 0); -- sfix51_En45
  SIGNAL b1multypeconvert1                : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL add_cast                         : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL add_cast_1                       : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL add_temp                         : signed(50 DOWNTO 0); -- sfix51_En44
  SIGNAL add_cast_2                       : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL add_cast_3                       : signed(49 DOWNTO 0); -- sfix50_En44
  SIGNAL add_temp_1                       : signed(50 DOWNTO 0); -- sfix51_En44
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16
  SIGNAL output_register                  : signed(15 DOWNTO 0); -- sfix16


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      input_register <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp(47 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 58);

  scaletypeconvert1 <= resize(shift_right(scale1(47 DOWNTO 0) + ( "0" & (scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32) & NOT scale1(32))), 32), 16);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(45 DOWNTO 0) + ( "0" & (a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30) & NOT a1sum1(30))), 30), 16);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 50);

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= resize(typeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);

  b2mul1 <= resize(delay_section1(0)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);

  b3mul1 <= resize(delay_section1(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);

  sub_cast <= inputconv1;
  sub_cast_1 <= resize(a2mul1, 50);
  sub_temp <= resize(sub_cast, 51) - resize(sub_cast_1, 51);
  a2sum1 <= sub_temp(49 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(a3mul1, 50);
  sub_temp_1 <= resize(sub_cast_2, 51) - resize(sub_cast_3, 51);
  a1sum1 <= sub_temp_1(49 DOWNTO 0);

  b1multypeconvert1 <= resize(b1mul1, 50);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(b2mul1, 50);
  add_temp <= resize(add_cast, 51) + resize(add_cast_1, 51);
  b2sum1 <= add_temp(49 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(b3mul1, 50);
  add_temp_1 <= resize(add_cast_2, 51) + resize(add_cast_3, 51);
  b1sum1 <= add_temp_1(49 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum1(49) & b1sum1(49 DOWNTO 0) + ( "0" & (b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44) & NOT b1sum1(44))), 44), 16);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
